#!/bin/bash

set -eo pipefail

PROG=$(basename "$0")
PROG_DIR=$(dirname "$0")

if [ -t 0 ] && [ -t 1 ]; then
    Red='\033[0;31m'
    Cyan='\033[0;36m'
    UnderlineON='\033[4m'
    UnderlineOFF='\033[24m'
    Bold='\033[1m'
    Reset='\033[0m'
else
    Red=
    Cyan=
    UnderlineON='`'
    UnderlineOFF='`'
    Bold=
    Reset=
fi

function log {
    echo -e "${Cyan}[+] $1${Reset}"
}

function usage {
    cat <<EOF 1>&2
usage: $PROG [options...] SOURCEDIR
Options:
  -i IMAGE     Name of the docker image (including tag) to use as package build environment.
  -c PROGRAM   Use a custom container engine.
  -o DIR       Destination directory to store packages to.
  -d DIR       Directory that contains other deb packages that need to be installed before build.
  -p profiles  Specify the profiles to build (e.g. nocheck). Takes a comma separated list.
  -C           Use ccache to cache compiled objects.
  -L           Run Lintian after a successful build.
  -B           Run blhc after a successful build.
  -t           Reset file modification timestamps to changelog entry.
EOF
    exit 1
}

function fatal {
    echo -e "${Red}[!]${Reset} ${Bold}$PROG${Reset}: ${Red}${1:-"Unknown Error"}${Reset}" 1>&2
    exit 1
}

function abspath {
    cd "$1" && pwd
}

function sanitize_string {
    local str=${1//_/}
    str=${str// /_}
    echo "${str//[^a-zA-Z0-9_]/-}"
}


###########################################################################

[[ $# -eq 0 ]] && usage

while getopts "c:i:o:p:d:htBCL" opt; do
    case $opt in
        c)
            tool="$OPTARG"
            ;;
        i)
            image="$OPTARG"
            ;;
        o)
            outdir="$OPTARG"
            ;;
        p)
            profiles="$OPTARG"
            ;;
        d)
            depdir="$OPTARG"
            ;;
        t)
            reset_timestamps=1
            ;;
        B)
            run_blhc=1
            ;;
        C)
            use_ccache=1
            ;;
        L)
            run_lintian=1
            ;;
        h)
            usage
            ;;
        *)
            usage
            ;;
    esac
done

shift $((OPTIND - 1))
[[ $# -eq 0 ]] && fatal "source directory not specified"
srcdir=$1
shift
extra_args=("$@")
[[ $# -ne 0 ]] && fatal "invalid trailing command line argument(s): ${extra_args[*]}"

if [[ ! "$tool" ]]; then
    if command -v podman >/dev/null 2>&1; then
        tool='podman'
    elif command -v docker >/dev/null 2>&1; then
        tool='docker'
    elif command -v distrobox-host-exec >/dev/null 2>&1; then
        if distrobox-host-exec podman --version >/dev/null 2>&1; then
            tool='distrobox-host-exec podman'
        elif distrobox-host-exec docker --version >/dev/null 2>&1; then
            tool='distrobox-host-exec docker'
        fi
    fi
fi

[[ ! "$tool" ]] && fatal "neither podman nor docker found"
tool_version=$($tool --version)

docker_args="--interactive --tty "

# Check that mandatory parameters are valid
[[ !    "$outdir"        ]] && fatal "output directory was not given (-o DIR)"
[[ ! -d "$outdir"        ]] && fatal "output directory ${UnderlineON}${outdir}${UnderlineOFF} does not exist"
[[ !    "$srcdir"        ]] && fatal "source directory not given"
[[ ! -r "$srcdir/debian" ]] && fatal "source directory ${UnderlineON}${srcdir}${UnderlineOFF} does not contain debian sub directory"
[[ !    "$image"         ]] && fatal "docker image name not given (-i IMAGE)"

# Check that optional parameters are valid
if [[ "$depdir" ]]; then
    [[ ! -e "$depdir" ]] && fatal "dependency directory ${UnderlineON}${depdir}${UnderlineOFF} given but does not exist"
    [[ ! -d "$depdir" ]] && fatal "dependency directory ${UnderlineON}${depdir}${UnderlineOFF} given but is not a directory"
    docker_args+="--volume $(abspath "$depdir"):/dependencies:ro "
fi

docker_args+="--volume $(abspath "$srcdir"):/source-ro:ro "
docker_args+="--volume $(abspath "$outdir"):/output "
docker_args+="--volume $(cd "$PROG_DIR"; pwd)/build-helper.sh:/build-helper.sh:ro "
docker_args+="--mount type=tmpfs,tmpfs-size=4G,destination=/tmp "

# Pass current UID and GID to container, so that it can change the
# ownership of output files which are otherwise written to outdir as
# root
CURR_UID=$(id -u)
CURR_GID=$(id -g)
[[ "$tool_version" =~ "Docker" ]] && docker_args+="--env USER=${CURR_UID} --env GROUP=${CURR_GID} "

# Comment following out if you want to keep container after execution
# for debugging
docker_args+="--rm "

# pass build profiles to use
if [[ "$profiles" ]]; then
    docker_args+="--env DEB_BUILD_PROFILES=$profiles --env DEB_BUILD_OPTIONS=$profiles "
fi

sanitized_image_name=$(sanitize_string "$image")

# share apt package cache
docker_args+="--volume cdebb__${sanitized_image_name}__apt:/var/cache/apt/archives "

# pass whether to use ccache
if [[ "$use_ccache" ]]; then
    docker_args+="--env USE_CCACHE=1 --volume cdebb__${sanitized_image_name}__ccache:/ccache_dir "
fi

# pass whether to run Lintian
if [[ "$run_lintian" ]]; then
    docker_args+="--env RUN_LINTIAN=1 "
fi

# pass whether to run blhc
if [[ "$run_blhc" ]]; then
    docker_args+="--env RUN_BLHC=1 "
fi

# pass whether to reset timestamps
if [[ "$reset_timestamps" ]]; then
    docker_args+="--env RESET_TIMESTAMPS=1 "
fi

# disable any selinux stuff while using rh and derivates with podman
[[ "$tool_version" =~ "podman" ]] && docker_args+="--security-opt label=disable "

cmd="$tool run $docker_args $image /build-helper.sh"

log "Running '$tool':"
log "$cmd"

exec $cmd
